//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckEngineTaller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacion
    {
        public string EstacionNombre { get; set; }
        public int ActividadId { get; set; }
        public int EstacionId { get; set; }
    
        public virtual Actividad Actividad { get; set; }
    }
}
